# Generated by Django 4.2.7 on 2023-12-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0002_producto_alter_user_email_opinioncliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opinioncliente',
            name='opinion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='urlImg',
            field=models.URLField(default=''),
        ),
    ]
