# Generated by Django 4.2.7 on 2023-12-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_carritocompras_cantidad_opinioncliente_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='urlImg',
            field=models.CharField(max_length=300),
        ),
    ]
